// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRE0n-jmFWTl97wEX24pXsH6aH8O4GTJs',
    appId: '1:791386930559:web:092fd5307bc728417dae4a',
    messagingSenderId: '791386930559',
    projectId: 'roomutilization',
    authDomain: 'roomutilization.firebaseapp.com',
    storageBucket: 'roomutilization.appspot.com',
    measurementId: 'G-STMV3CMGEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK1VWDa7DFD39Nv6XsuykWZ6F0t6gUWz4',
    appId: '1:791386930559:android:3907a66c9d2035287dae4a',
    messagingSenderId: '791386930559',
    projectId: 'roomutilization',
    storageBucket: 'roomutilization.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRE0n-jmFWTl97wEX24pXsH6aH8O4GTJs',
    appId: '1:791386930559:web:034f8c48073dd43a7dae4a',
    messagingSenderId: '791386930559',
    projectId: 'roomutilization',
    authDomain: 'roomutilization.firebaseapp.com',
    storageBucket: 'roomutilization.appspot.com',
    measurementId: 'G-4S4VGEC1T4',
  );
}
